name: Catalog

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "NR1 Nerdpack Name"
        required: true
      version:
        description: "Version to update"
        required: true
      ref:
        description: "Commit SHA to update the submodule to"
        required: true
      user:
        description: "User who initiated the deployment"
        required: true
      action:
        description: "Action to take with submodule. Possible values: add, update"
        required: true
        default: "update"
      url:
        description: "If action == `add`, must supply URL of repo"
        required: false
jobs:

  job-trigger-catalog-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke nr1-catalog PR workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Generate Catalog PR
          repo: newrelic/nr1-catalog
          token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          ref: master
          inputs: '{ "appName": "${{ github.event.inputs.appName }}", "version": "${{ github.event.inputs.version }}", "ref": "${{ github.event.inputs.ref }}", "user": "${{ github.event.inputs.user }}", "action": "${{ github.event.inputs.action }}", "url": "${{ github.event.inputs.url }}" }'
